# -*- mode: ruby -*-
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
    config.vm.provider "virtualbox" do |vb|
        vb.name = "chef-sandbox"
        vb.customize ["modifyvm", :id, "--memory", 512, "--cpus", 2]
    end
    # host-only network
    config.vm.network :private_network, ip: "192.168.50.10"
end
