---
driver:
  name: ec2
  region: us-east-1

transport:
  ssh_key: ~/.ssh/<%= ENV.fetch('KEY_USER', "") %>
  username: ["ec2-user"]

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.17.44
  data_path: test/shared

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: <%= ENV.fetch('EC2_IMAGE_ID', "ami-2a69aa47") %>
      instance_type: <%= ENV.fetch('EC2_INSTANCE_TYPE', "t2.micro") %>

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[example::default]
    attributes:
        {example:
                {update_version: '1.1'
                }
        }
