---
driver:
  name: digitalocean

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.17.44
  data_path: test/shared

platforms:
  - name: example
    driver_config:
      region: sfo2
      size: <%= ENV.fetch('DIGITALOCEAN_FLAVOR', "2gb") %>
      private_networking: false
      image: ubuntu-14-04-x64
      server_name: <%= ENV.fetch('INSTANCE_NAME', "example") %>

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[example::default]
    attributes:
        {example:
                {update_version: '1.1'
                }
        }
