---
driver:
  name: ec2

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.17.44
  data_path: test/shared
transport:
   ssh_key: ~/.ssh/<%= ENV.fetch('KEY_USER', "") %>

platforms:
  - name: ubuntu-14.04
    driver:
      region: us-east-1
      image_id: <%= ENV.fetch('EC2_IMAGE_ID', "ami-2a69aa47") %>
      instance_type: <%= ENV.fetch('EC2_INSTANCE_TYPE', "t2.micro") %>
      server_name: <%= ENV.fetch('INSTANCE_NAME', "example") %>
      transport.username: ["ec2-user"]

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[example::default]
    attributes:
        {example:
                {update_version: '1.1'
                }
        }
