source 'https://rubygems.org'
# source 'https://ruby.taobao.org/'

gem 'kitchen-docker', '= 2.6.0'
gem 'test-kitchen', '= 1.19.0'
gem 'kitchen-digitalocean'
gem 'kitchen-vagrant'
gem 'kitchen-ec2'

gem 'berkshelf', '= 6.3.1'

gem 'foodcritic', '~> 4.0.0'
gem 'rubocop', '~> 0.48.1'
